In [118]:
import pandas as pd
df=pd.read_csv('students_data.csv')

In [119]:
#Display the last 5 rows.
df.tail(6)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
9,10,Meena,Female,16,10,92,90,89,94,Delhi
10,11,Rohit,Male,15,9,74,78,76,80,Mumbai
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
12,13,Sahil,Male,16,10,66,68,64,72,Chennai
13,14,Kavya,Female,15,9,91,93,95,97,Delhi
14,15,Deep,Male,17,11,58,62,61,59,Mumbai

In [120]:
#Display the last 5 rows.
df.tail(5)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
10,11,Rohit,Male,15,9,74,78,76,80,Mumbai
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
12,13,Sahil,Male,16,10,66,68,64,72,Chennai
13,14,Kavya,Female,15,9,91,93,95,97,Delhi
14,15,Deep,Male,17,11,58,62,61,59,Mumbai

In [127]:

#Display the first 5 rows
df.head(6)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
1,2,Riya,Female,15,9,88,92,84,95,Delhi
2,3,Rahul,Male,17,11,67,70,72,60,Mumbai
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
4,5,Arjun,Male,15,9,56,60,58,65,Chennai
5,6,Priya,Female,17,11,95,94,96,98,Delhi

In [128]:
#Find the shape of the dataset.
df.shape

(15, 10)

In [129]:
#Show all column names.
df.columns

Index(['StudentID', 'Name', 'Gender', 'Age', 'Class', 'Math', 'English',
       'Science', 'Computer', 'City'],
      dtype='object')

In [114]:
#Check the data types of each column.
df.dtypes

StudentID     int64
Name         object
Gender       object
Age           int64
Class         int64
Math          int64
English       int64
Science       int64
Computer      int64
City         object
dtype: object

In [115]:
#Find the mean of the "Age" column.
df['Age'].mean()

np.float64(16.0)

In [116]:
#display only the Name column.
print(df['Name'])

0       Amit
1       Riya
2      Rahul
3      Sneha
4      Arjun
5      Priya
6      Karan
7     Anjali
8     Vikram
9      Meena
10     Rohit
11     Pooja
12     Sahil
13     Kavya
14      Deep
Name: Name, dtype: object

In [117]:
#Show students who are 16 years old.
df[df['Age'] == 16]

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
6,7,Karan,Male,16,10,72,75,70,68,Mumbai
9,10,Meena,Female,16,10,92,90,89,94,Delhi
12,13,Sahil,Male,16,10,66,68,64,72,Chennai

In [121]:
#Show only Female students.
df[df['Gender'] == 'Female']

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
1,2,Riya,Female,15,9,88,92,84,95,Delhi
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
5,6,Priya,Female,17,11,95,94,96,98,Delhi
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata
9,10,Meena,Female,16,10,92,90,89,94,Delhi
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
13,14,Kavya,Female,15,9,91,93,95,97,Delhi

In [122]:
#Show students from Kolkata.
df[df['City'] == 'Kolkata']

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata

In [123]:
#Show students from Class 10.
df[df['Class'] == 10]

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
6,7,Karan,Male,16,10,72,75,70,68,Mumbai
9,10,Meena,Female,16,10,92,90,89,94,Delhi
12,13,Sahil,Male,16,10,66,68,64,72,Chennai

In [124]:
#Show students who scored more than 80 in Math.
df[df['Math'] >=80]

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
1,2,Riya,Female,15,9,88,92,84,95,Delhi
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
5,6,Priya,Female,17,11,95,94,96,98,Delhi
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata
9,10,Meena,Female,16,10,92,90,89,94,Delhi
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
13,14,Kavya,Female,15,9,91,93,95,97,Delhi

In [125]:
#Show Female students who are 15 years old.
df[(df['Gender'] == 'Female')&(df['Age'] ==15)]

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
1,2,Riya,Female,15,9,88,92,84,95,Delhi
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata
13,14,Kavya,Female,15,9,91,93,95,97,Delhi

In [126]:

#Show students who scored less than 70 in Science.
df[df['Science'] >=70]

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
1,2,Riya,Female,15,9,88,92,84,95,Delhi
2,3,Rahul,Male,17,11,67,70,72,60,Mumbai
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
5,6,Priya,Female,17,11,95,94,96,98,Delhi
6,7,Karan,Male,16,10,72,75,70,68,Mumbai
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata
9,10,Meena,Female,16,10,92,90,89,94,Delhi
10,11,Rohit,Male,15,9,74,78,76,80,Mumbai
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
13,14,Kavya,Female,15,9,91,93,95,97,Delhi