In [22]:
import pandas as pd
df=pd.read_csv('students_data.csv')

In [38]:
#Display the last 5 rows.
df.tail(6)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
9,10,Meena,Female,16,10,92,90,89,94,Delhi
10,11,Rohit,Male,15,9,74,78,76,80,Mumbai
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
12,13,Sahil,Male,16,10,66,68,64,72,Chennai
13,14,Kavya,Female,15,9,91,93,95,97,Delhi
14,15,Deep,Male,17,11,58,62,61,59,Mumbai

In [40]:
#Display the last 5 rows.
df.tail(5)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
10,11,Rohit,Male,15,9,74,78,76,80,Mumbai
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
12,13,Sahil,Male,16,10,66,68,64,72,Chennai
13,14,Kavya,Female,15,9,91,93,95,97,Delhi
14,15,Deep,Male,17,11,58,62,61,59,Mumbai

In [41]:

#Display the first 5 rows
df.head(6)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
1,2,Riya,Female,15,9,88,92,84,95,Delhi
2,3,Rahul,Male,17,11,67,70,72,60,Mumbai
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
4,5,Arjun,Male,15,9,56,60,58,65,Chennai
5,6,Priya,Female,17,11,95,94,96,98,Delhi

In [43]:
#Find the shape of the dataset.
df.shape

(15, 10)

In [27]:
#Show all column names.

In [28]:
#Check the data types of each column#.

In [29]:
#Find the mean of the "Age" column.

In [30]:
#display only the Name column.

In [31]:
#Show students who are 16 years old.

In [32]:
#Show only Female students.

In [33]:
#Show students from Kolkata.

In [34]:
#Show students from Class 10.

In [35]:
#Show students who scored more than 80 in Math.

In [36]:
#Show Female students who are 15 years old.

In [37]:

#Show students who scored less than 70 in Science.