In [196]:
import pandas as pd
df=pd.read_csv('students_data.csv')

In [197]:
#Display the last 5 rows.
df.tail(6)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
9,10,Meena,Female,16,10,92,90,89,94,Delhi
10,11,Rohit,Male,15,9,74,78,76,80,Mumbai
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
12,13,Sahil,Male,16,10,66,68,64,72,Chennai
13,14,Kavya,Female,15,9,91,93,95,97,Delhi
14,15,Deep,Male,17,11,58,62,61,59,Mumbai

In [198]:
#Display the last 5 rows.
df.tail(5)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
10,11,Rohit,Male,15,9,74,78,76,80,Mumbai
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
12,13,Sahil,Male,16,10,66,68,64,72,Chennai
13,14,Kavya,Female,15,9,91,93,95,97,Delhi
14,15,Deep,Male,17,11,58,62,61,59,Mumbai

In [199]:

#Display the first 5 rows
df.head(6)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
1,2,Riya,Female,15,9,88,92,84,95,Delhi
2,3,Rahul,Male,17,11,67,70,72,60,Mumbai
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
4,5,Arjun,Male,15,9,56,60,58,65,Chennai
5,6,Priya,Female,17,11,95,94,96,98,Delhi

In [200]:
#Find the shape of the dataset.
df.shape

(15, 10)

In [201]:
#Show all column names.
df.columns

Index(['StudentID', 'Name', 'Gender', 'Age', 'Class', 'Math', 'English',
       'Science', 'Computer', 'City'],
      dtype='object')

In [202]:
#Check the data types of each column.
df.dtypes

StudentID     int64
Name         object
Gender       object
Age           int64
Class         int64
Math          int64
English       int64
Science       int64
Computer      int64
City         object
dtype: object

In [203]:
#Find the mean of the "Age" column.
df['Age'].mean()

np.float64(16.0)

In [204]:
#display only the Name column.
print(df['Name'])

0       Amit
1       Riya
2      Rahul
3      Sneha
4      Arjun
5      Priya
6      Karan
7     Anjali
8     Vikram
9      Meena
10     Rohit
11     Pooja
12     Sahil
13     Kavya
14      Deep
Name: Name, dtype: object

In [205]:
#Show students who are 16 years old.
df[df['Age'] == 16]

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
6,7,Karan,Male,16,10,72,75,70,68,Mumbai
9,10,Meena,Female,16,10,92,90,89,94,Delhi
12,13,Sahil,Male,16,10,66,68,64,72,Chennai

In [206]:
#Show only Female students.
df[df['Gender'] == 'Female']

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
1,2,Riya,Female,15,9,88,92,84,95,Delhi
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
5,6,Priya,Female,17,11,95,94,96,98,Delhi
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata
9,10,Meena,Female,16,10,92,90,89,94,Delhi
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
13,14,Kavya,Female,15,9,91,93,95,97,Delhi

In [207]:
#Show students from Kolkata.
df[df['City'] == 'Kolkata']

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata

In [208]:
#Show students from Class 10.
df[df['Class'] == 10]

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
6,7,Karan,Male,16,10,72,75,70,68,Mumbai
9,10,Meena,Female,16,10,92,90,89,94,Delhi
12,13,Sahil,Male,16,10,66,68,64,72,Chennai

In [209]:
#Show students who scored more than 80 in Math.
df[df['Math'] >=80]

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
1,2,Riya,Female,15,9,88,92,84,95,Delhi
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
5,6,Priya,Female,17,11,95,94,96,98,Delhi
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata
9,10,Meena,Female,16,10,92,90,89,94,Delhi
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
13,14,Kavya,Female,15,9,91,93,95,97,Delhi

In [210]:
#Show Female students who are 15 years old.
df[(df['Gender'] == 'Female')&(df['Age'] ==15)]

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
1,2,Riya,Female,15,9,88,92,84,95,Delhi
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata
13,14,Kavya,Female,15,9,91,93,95,97,Delhi

In [211]:

#Show students who scored less than 70 in Science.
df[df['Science'] >=70]

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
1,2,Riya,Female,15,9,88,92,84,95,Delhi
2,3,Rahul,Male,17,11,67,70,72,60,Mumbai
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
5,6,Priya,Female,17,11,95,94,96,98,Delhi
6,7,Karan,Male,16,10,72,75,70,68,Mumbai
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata
9,10,Meena,Female,16,10,92,90,89,94,Delhi
10,11,Rohit,Male,15,9,74,78,76,80,Mumbai
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
13,14,Kavya,Female,15,9,91,93,95,97,Delhi

In [212]:
#Find the average of the Math column.
print(df['Math'].mean())

77.4

In [213]:
#Find the average of all subject columns.
print(df[['Math','Science','English','Computer']].mean().round(2))

Math        77.40
Science     77.87
English     79.00
Computer    81.27
dtype: float64

In [214]:
#Find the highest score in Math.
print(df['Math'].max())

95

In [215]:
#Find the lowest score in English.
print(df['English'].min())

60

In [216]:
    
#Count total number of Male students.
print(df[df['Gender'] == 'Male'].shape[0])

8

In [217]:
#Count students city-wise.
df['City'].value_counts()

City
Kolkata    4
Delhi      4
Mumbai     4
Chennai    3
Name: count, dtype: int64

In [218]:
#Find average Math score by Gender.
df.groupby('Gender')['Math'].mean().round(2)

Gender
Female    90.00
Male      66.38
Name: Math, dtype: float64

In [219]:
#Find average Science score by Class.
df.groupby('Gender')['Science'].mean().round(2)

Gender
Female    89.14
Male      68.00
Name: Science, dtype: float64

In [220]:
#Sort the dataset by Math in descending order.
df.sort_values(by='Math', ascending=False,)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
5,6,Priya,Female,17,11,95,94,96,98,Delhi
9,10,Meena,Female,16,10,92,90,89,94,Delhi
13,14,Kavya,Female,15,9,91,93,95,97,Delhi
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
1,2,Riya,Female,15,9,88,92,84,95,Delhi
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
10,11,Rohit,Male,15,9,74,78,76,80,Mumbai
6,7,Karan,Male,16,10,72,75,70,68,Mumbai
2,3,Rahul,Male,17,11,67,70,72,60,Mumbai
12,13,Sahil,Male,16,10,66,68,64,72,Chennai
8,9,Vikram,Male,17,11,60,65,63,70,Chennai
14,15,Deep,Male,17,11,58,62,61,59,Mumbai
4,5,Arjun,Male,15,9,56,60,58,65,Chennai

In [221]:
#Sort the dataset by Age in ascending order.
df.sort_values(by='Age',ascending=True)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City
1,2,Riya,Female,15,9,88,92,84,95,Delhi
4,5,Arjun,Male,15,9,56,60,58,65,Chennai
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata
10,11,Rohit,Male,15,9,74,78,76,80,Mumbai
13,14,Kavya,Female,15,9,91,93,95,97,Delhi
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata
6,7,Karan,Male,16,10,72,75,70,68,Mumbai
0,1,Amit,Male,16,10,78,85,80,90,Kolkata
12,13,Sahil,Male,16,10,66,68,64,72,Chennai
9,10,Meena,Female,16,10,92,90,89,94,Delhi
5,6,Priya,Female,17,11,95,94,96,98,Delhi
2,3,Rahul,Male,17,11,67,70,72,60,Mumbai
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata
8,9,Vikram,Male,17,11,60,65,63,70,Chennai
14,15,Deep,Male,17,11,58,62,61,59,Mumbai

In [222]:
#Create a new column Total (sum of all subjects).
df['total']=df['Math']+df['Science']+df['English']+df['Computer']
df

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City,total
0,1,Amit,Male,16,10,78,85,80,90,Kolkata,333
1,2,Riya,Female,15,9,88,92,84,95,Delhi,359
2,3,Rahul,Male,17,11,67,70,72,60,Mumbai,269
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata,362
4,5,Arjun,Male,15,9,56,60,58,65,Chennai,239
5,6,Priya,Female,17,11,95,94,96,98,Delhi,383
6,7,Karan,Male,16,10,72,75,70,68,Mumbai,285
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata,335
8,9,Vikram,Male,17,11,60,65,63,70,Chennai,258
9,10,Meena,Female,16,10,92,90,89,94,Delhi,365
10,11,Rohit,Male,15,9,74,78,76,80,Mumbai,308
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata,351
12,13,Sahil,Male,16,10,66,68,64,72,Chennai,270
13,14,Kavya,Female,15,9,91,93,95,97,Delhi,376
14,15,Deep,Male,17,11,58,62,61,59,Mumbai,240

In [223]:
#Create a new column Average.
df['average']=df['total']/4
df

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City,total,average
0,1,Amit,Male,16,10,78,85,80,90,Kolkata,333,83.25
1,2,Riya,Female,15,9,88,92,84,95,Delhi,359,89.75
2,3,Rahul,Male,17,11,67,70,72,60,Mumbai,269,67.25
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata,362,90.50
4,5,Arjun,Male,15,9,56,60,58,65,Chennai,239,59.75
5,6,Priya,Female,17,11,95,94,96,98,Delhi,383,95.75
6,7,Karan,Male,16,10,72,75,70,68,Mumbai,285,71.25
7,8,Anjali,Female,15,9,85,80,82,88,Kolkata,335,83.75
8,9,Vikram,Male,17,11,60,65,63,70,Chennai,258,64.50
9,10,Meena,Female,16,10,92,90,89,94,Delhi,365,91.25
10,11,Rohit,Male,15,9,74,78,76,80,Mumbai,308,77.00
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata,351,87.75
12,13,Sahil,Male,16,10,66,68,64,72,Chennai,270,67.50
13,14,Kavya,Female,15,9,91,93,95,97,Delhi,376,94.00
14,15,Deep,Male,17,11,58,62,61,59,Mumbai,240,60.00

In [224]:
#Show students whose Average is greater than 85.
df[df['average']>=85]

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City,total,average
1,2,Riya,Female,15,9,88,92,84,95,Delhi,359,89.75
3,4,Sneha,Female,16,10,90,88,91,93,Kolkata,362,90.50
5,6,Priya,Female,17,11,95,94,96,98,Delhi,383,95.75
9,10,Meena,Female,16,10,92,90,89,94,Delhi,365,91.25
11,12,Pooja,Female,17,11,89,85,87,90,Kolkata,351,87.75
13,14,Kavya,Female,15,9,91,93,95,97,Delhi,376,94.00

In [225]:
#Display top 3 students based on Total marks.
df.sort_values(by='total', ascending=False).head(3)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City,total,average
5,6,Priya,Female,17,11,95,94,96,98,Delhi,383,95.75
13,14,Kavya,Female,15,9,91,93,95,97,Delhi,376,94.00
9,10,Meena,Female,16,10,92,90,89,94,Delhi,365,91.25

In [226]:
#Display bottom 3 students based on Total marks.
df.sort_values(by='total', ascending=True).head(3)

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City,total,average
4,5,Arjun,Male,15,9,56,60,58,65,Chennai,239,59.75
14,15,Deep,Male,17,11,58,62,61,59,Mumbai,240,60.00
8,9,Vikram,Male,17,11,60,65,63,70,Chennai,258,64.50

In [227]:
#Group by City and find average Total marks.
df.groupby('City')['average'].mean().round(2)

City
Chennai    63.92
Delhi      92.69
Kolkata    86.31
Mumbai     68.88
Name: average, dtype: float64

In [228]:
#Group by Gender and find highest Math score.
df.groupby('Gender')['Math'].mean().round(2).sort_values(ascending=False)

Gender
Female    90.00
Male      66.38
Name: Math, dtype: float64

In [229]:
#Find the highest scoring student in each Class and display name
df.loc[df.groupby('Class')['total'].idxmax(), ['Class', 'Name', 'total']]

    Class   Name  total
13      9  Kavya    376
9      10  Meena    365
5      11  Priya    383

In [230]:
#Create a new column Result (Pass if Average ≥ 60, else Fail).
df['Result'] = df['average'].apply(lambda x: 'Pass' if x >= 60 else 'Fail')

In [231]:
#Count how many students failed.
df[df['Result'] == 'Fail'].shape[0]

1

In [232]:
#Find Male and Female count city-wise.
df.groupby(['City', 'Gender']).size()

City     Gender
Chennai  Male      3
Delhi    Female    4
Kolkata  Female    3
         Male      1
Mumbai   Male      4
dtype: int64

In [233]:
#Check if there are any duplicate rows.
df.duplicated(['Age'])

0     False
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
dtype: bool

In [234]:
#Set StudentID as index.
df['StudentID'] = df['Name'] + '_' + df['Age'].astype(str)
df.set_index('StudentID', inplace=True)
df

,Name,Gender,Age,Class,Math,English,Science,Computer,City,total,average,Result
StudentID,,,,,,,,,,,,
Amit_16,Amit,Male,16,10,78,85,80,90,Kolkata,333,83.25,Pass
Riya_15,Riya,Female,15,9,88,92,84,95,Delhi,359,89.75,Pass
Rahul_17,Rahul,Male,17,11,67,70,72,60,Mumbai,269,67.25,Pass
Sneha_16,Sneha,Female,16,10,90,88,91,93,Kolkata,362,90.50,Pass
Arjun_15,Arjun,Male,15,9,56,60,58,65,Chennai,239,59.75,Fail
Priya_17,Priya,Female,17,11,95,94,96,98,Delhi,383,95.75,Pass
Karan_16,Karan,Male,16,10,72,75,70,68,Mumbai,285,71.25,Pass
Anjali_15,Anjali,Female,15,9,85,80,82,88,Kolkata,335,83.75,Pass
Vikram_17,Vikram,Male,17,11,60,65,63,70,Chennai,258,64.50,Pass
Meena_16,Meena,Female,16,10,92,90,89,94,Delhi,365,91.25,Pass
Rohit_15,Rohit,Male,15,9,74,78,76,80,Mumbai,308,77.00,Pass
Pooja_17,Pooja,Female,17,11,89,85,87,90,Kolkata,351,87.75,Pass
Sahil_16,Sahil,Male,16,10,66,68,64,72,Chennai,270,67.50,Pass
Kavya_15,Kavya,Female,15,9,91,93,95,97,Delhi,376,94.00,Pass
Deep_17,Deep,Male,17,11,58,62,61,59,Mumbai,240,60.00,Pass

In [235]:
#Reset the index.
df.reset_index(inplace=True)
df.reset_index(drop=True, inplace=True)
df

,StudentID,Name,Gender,Age,Class,Math,English,Science,Computer,City,total,average,Result
0,Amit_16,Amit,Male,16,10,78,85,80,90,Kolkata,333,83.25,Pass
1,Riya_15,Riya,Female,15,9,88,92,84,95,Delhi,359,89.75,Pass
2,Rahul_17,Rahul,Male,17,11,67,70,72,60,Mumbai,269,67.25,Pass
3,Sneha_16,Sneha,Female,16,10,90,88,91,93,Kolkata,362,90.50,Pass
4,Arjun_15,Arjun,Male,15,9,56,60,58,65,Chennai,239,59.75,Fail
5,Priya_17,Priya,Female,17,11,95,94,96,98,Delhi,383,95.75,Pass
6,Karan_16,Karan,Male,16,10,72,75,70,68,Mumbai,285,71.25,Pass
7,Anjali_15,Anjali,Female,15,9,85,80,82,88,Kolkata,335,83.75,Pass
8,Vikram_17,Vikram,Male,17,11,60,65,63,70,Chennai,258,64.50,Pass
9,Meena_16,Meena,Female,16,10,92,90,89,94,Delhi,365,91.25,Pass
10,Rohit_15,Rohit,Male,15,9,74,78,76,80,Mumbai,308,77.00,Pass
11,Pooja_17,Pooja,Female,17,11,89,85,87,90,Kolkata,351,87.75,Pass
12,Sahil_16,Sahil,Male,16,10,66,68,64,72,Chennai,270,67.50,Pass
13,Kavya_15,Kavya,Female,15,9,91,93,95,97,Delhi,376,94.00,Pass
14,Deep_17,Deep,Male,17,11,58,62,61,59,Mumbai,240,60.00,Pass

In [236]:
#remove  Class  column.

df = df.drop(columns=['Class'])
df

,StudentID,Name,Gender,Age,Math,English,Science,Computer,City,total,average,Result
0,Amit_16,Amit,Male,16,78,85,80,90,Kolkata,333,83.25,Pass
1,Riya_15,Riya,Female,15,88,92,84,95,Delhi,359,89.75,Pass
2,Rahul_17,Rahul,Male,17,67,70,72,60,Mumbai,269,67.25,Pass
3,Sneha_16,Sneha,Female,16,90,88,91,93,Kolkata,362,90.50,Pass
4,Arjun_15,Arjun,Male,15,56,60,58,65,Chennai,239,59.75,Fail
5,Priya_17,Priya,Female,17,95,94,96,98,Delhi,383,95.75,Pass
6,Karan_16,Karan,Male,16,72,75,70,68,Mumbai,285,71.25,Pass
7,Anjali_15,Anjali,Female,15,85,80,82,88,Kolkata,335,83.75,Pass
8,Vikram_17,Vikram,Male,17,60,65,63,70,Chennai,258,64.50,Pass
9,Meena_16,Meena,Female,16,92,90,89,94,Delhi,365,91.25,Pass
10,Rohit_15,Rohit,Male,15,74,78,76,80,Mumbai,308,77.00,Pass
11,Pooja_17,Pooja,Female,17,89,85,87,90,Kolkata,351,87.75,Pass
12,Sahil_16,Sahil,Male,16,66,68,64,72,Chennai,270,67.50,Pass
13,Kavya_15,Kavya,Female,15,91,93,95,97,Delhi,376,94.00,Pass
14,Deep_17,Deep,Male,17,58,62,61,59,Mumbai,240,60.00,Pass

In [237]:

#Create a new DataFrame with only numeric columns.
numeric_df = df.select_dtypes(include='number')
numeric_df

    Age  Math  English  Science  Computer  total  average
0    16    78       85       80        90    333    83.25
1    15    88       92       84        95    359    89.75
2    17    67       70       72        60    269    67.25
3    16    90       88       91        93    362    90.50
4    15    56       60       58        65    239    59.75
5    17    95       94       96        98    383    95.75
6    16    72       75       70        68    285    71.25
7    15    85       80       82        88    335    83.75
8    17    60       65       63        70    258    64.50
9    16    92       90       89        94    365    91.25
10   15    74       78       76        80    308    77.00
11   17    89       85       87        90    351    87.75
12   16    66       68       64        72    270    67.50
13   15    91       93       95        97    376    94.00
14   17    58       62       61        59    240    60.00

In [238]:
#Find correlation between Math and Science.
correlation = df['Math'].corr(df['Science'])
print(f"Correlation between Math and Science: {correlation:.2f}")

Correlation between Math and Science: 0.98

In [239]:
#Create a ranking column based on Average marks.
df['rank'] = df['average'].rank(ascending=False)
df.set_index('rank')
df

,StudentID,Name,Gender,Age,Math,English,Science,Computer,City,total,average,Result,rank
0,Amit_16,Amit,Male,16,78,85,80,90,Kolkata,333,83.25,Pass,8.0
1,Riya_15,Riya,Female,15,88,92,84,95,Delhi,359,89.75,Pass,5.0
2,Rahul_17,Rahul,Male,17,67,70,72,60,Mumbai,269,67.25,Pass,12.0
3,Sneha_16,Sneha,Female,16,90,88,91,93,Kolkata,362,90.50,Pass,4.0
4,Arjun_15,Arjun,Male,15,56,60,58,65,Chennai,239,59.75,Fail,15.0
5,Priya_17,Priya,Female,17,95,94,96,98,Delhi,383,95.75,Pass,1.0
6,Karan_16,Karan,Male,16,72,75,70,68,Mumbai,285,71.25,Pass,10.0
7,Anjali_15,Anjali,Female,15,85,80,82,88,Kolkata,335,83.75,Pass,7.0
8,Vikram_17,Vikram,Male,17,60,65,63,70,Chennai,258,64.50,Pass,13.0
9,Meena_16,Meena,Female,16,92,90,89,94,Delhi,365,91.25,Pass,3.0
10,Rohit_15,Rohit,Male,15,74,78,76,80,Mumbai,308,77.00,Pass,9.0
11,Pooja_17,Pooja,Female,17,89,85,87,90,Kolkata,351,87.75,Pass,6.0
12,Sahil_16,Sahil,Male,16,66,68,64,72,Chennai,270,67.50,Pass,11.0
13,Kavya_15,Kavya,Female,15,91,93,95,97,Delhi,376,94.00,Pass,2.0
14,Deep_17,Deep,Male,17,58,62,61,59,Mumbai,240,60.00,Pass,14.0

In [247]:
#Find the student with highest Computer score.
df[df['Computer'] == df['Computer'].max()]

,StudentID,Name,Gender,Age,Math,English,Science,Computer,City,total,average,Result,rank
5,Priya_17,Priya,Female,17,95,94,96,98,Delhi,383,95.75,Pass,1.0

In [ ]:
#Group by Age and find average Total marks.

In [ ]:
#Filter students where Math > 80 AND City = Delhi.

In [ ]:
#Calculate percentile rank based on Total marks.

In [ ]:
#Find top student from each City.

In [ ]:
#Create grade column using apply() (A/B/C/D).

In [ ]:
#Create a pivot table: City vs Gender → Average Math score.

In [ ]:
#Generate a full summary report (using describe() and info()).